version: '3'

services:
  envoy:
    image: envoyproxy/envoy:v1.21.0
    ports:
      - 9901:9901
      - 10000:10000
    volumes:
      - '${PWD}/envoy.yaml:/etc/envoy/envoy.yaml'
    depends_on:
      - nginx

  nginx:
    image: nginx:1.21.1-alpine
