version: '3'

services:
  vegeta:
    image: peterevans/vegeta:6.9.1
    command: |
      sh -c "
        echo 'GET http://envoy:10000' \
        | vegeta attack -rate=10000 -duration=10s \
        | tee results.bin \
        | vegeta report
      "
    working_dir: /work
    volumes:
      - '${PWD}:/work'
