version: '3'

services:
  envoy:
    image: envoyproxy/envoy:v1.21.0
    ports:
      - 9901:9901
      - 10000:10000
    volumes:
      - '${PWD}/envoy.yaml:/etc/envoy/envoy.yaml'
    depends_on:
      - node

  node:
    image: node:16.13.2-alpine
    command: node index.js
    ports:
      - 3000:3000
    volumes:
      - '${PWD}/index.js:/index.js'
